version: 1
formatters:
  std:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: std
loggers:
  ssr_ocl:
    handlers: [console]
    level: INFO
    propagate: False
root:
  handlers: [console]
  level: INFO
